export const customerConstants = {
    GET_CUSTOMERS_API_REQUEST: "GET_CUSTOMERS_API_REQUEST",
    GET_CUSTOMERS_API_SUCCESS: "GET_CUSTOMERS_API_SUCCESS",
    GET_CUSTOMERS_API_FAILURE: "GET_CUSTOMERS_API_FAILURE",

    ADD_CUSTOMER: "ADD_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",

    SORT_LIST: "SORT_LIST",
}